### ISSUE TITLE
Missing DockerFile in examples folder to create xeuscling

### ISSUE THREAD

**Issue by ranadewa** [pdeitel/CPlusPlus20ForProgrammers#1]
Hi,

In [C++ 20 Fundamentals: Running in a Jupyter Notebook](https://learning.oreilly.com/videos/c-20-fundamentals/9780136875185/9780136875185-CP20_Jupyter01_00) following command is executed inside examples dir.
```
docker build --rm -t xeuscling .
```
This assumes there is a DockerFile  on the examples directory. But currently there is none. 

![image](https://user-images.githubusercontent.com/36048530/89114042-ea615e80-d4aa-11ea-9b09-a18a14bde5ea.png)

Please add the DockerFile or instruct how to create this in order to get this work.

Thanks.

**Comment by pdeitel** [comment]
Hi @ranadewa, Sorry, just saw this as the notification wound up in my junk mail. This is the repository for our book, not the videos you're using. The docker file is in the repository for the videos in the docker subfolder: https://github.com/pdeitel/CPlusPlus20FundamentalsLiveLessons.

Best, 
Paul
